name: iPad_IPA_Builder
on:
  workflow_dispatch:

jobs:
  build_job:
    runs-on: macos-latest
    steps:
      - name: 1. Kodlari Cek
        uses: actions/checkout@v4

      - name: 2. Node Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Bagimliliklari Yukle
        run: |
          npm install -g expo-cli
          npm install

      - name: 4. Firebase Plist Hatasini Coz
        run: |
          printf '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>CLIENT_ID</key><string>test</string></dict></plist>' > GoogleService-Info.plist

      - name: 5. iOS Projesini Olustur
        run: npx expo prebuild --platform ios --no-install

      - name: 6. Xcode Build ve Paketleme
        run: |
          mkdir -p Payload
          cd ios
          
          # Workspace dosyasını bul (Hatalı kütüphaneleri elemek için derin arama)
          WORKSPACE_FILE=$(ls -d *.xcworkspace | grep -v "Pods" | head -n 1)
          # Şema ismini app.json'daki 'name' değeriyle eşliyoruz
          SCHEME_NAME="depremapp" 
          
          echo "Kullanilan Workspace: $WORKSPACE_FILE"
          echo "Kullanilan Scheme: $SCHEME_NAME"

          xcodebuild -workspace "$WORKSPACE_FILE" \
            -scheme "$SCHEME_NAME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ../build \
            -quiet
          
          cd ..
          APP_PATH=$(find build -name "*.app" -type d | head -n 1)
          cp -r "$APP_PATH" Payload/
          zip -r DepTime.ipa Payload

      - name: 7. Dosyayi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: DepTime-iPad-Installer
          path: DepTime.ipa